---
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit
    rev: v4.6.0
    hooks:
      - id: validate_manifest
        name: 🛠️ pre-commit · Validate pre-commit configuration
  - hooks:
      - id: check-case-conflict
        name: 🛠️ pre-commit · Check for case conflicts
      - id: check-merge-conflict
        name: 🛠️ pre-commit · Check for merge conflicts
      - id: check-yaml
        name: 🛠️ pre-commit · Check YAML files
      - id: end-of-file-fixer
        name: 🛠️ pre-commit · Fix end of file
      - id: mixed-line-ending
        name: 🛠️ pre-commit · Check mixed line endings
      - id: trailing-whitespace
        name: 🛠️ pre-commit · Check trailing whitespace
      - id: check-json
        name: 🛠️ pre-commit · Check JSON files
      - id: check-added-large-files
        name: 🛠️ pre-commit · Check for large files
      - id: check-xml
        name: 🛠️ pre-commit · Check XML files
      - id: check-toml
        name: 🛠️ pre-commit · Check TOML files
      - args: ["--autofix", "--indent=4"]
        name: 🛠️ pre-commit · Check and fix JSON files
        id: pretty-format-json
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
  - hooks:
      - id: gitleaks
        name: 🔒 security · Detect hardcoded secrets
    repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
  - hooks:
      - additional_dependencies:
          - validate-pyproject-schema-store[all]
        id: validate-pyproject
        name: 🐍 validate-pyproject · Validate pyproject.toml
    repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
  - repo: https://github.com/myint/eradicate
    rev: 3.0.1
    hooks:
      - id: eradicate
        args: []
        name: 🐍 eradicate · Remove dead code
  - hooks:
      - args: [ --fix , --config, ./pyproject.toml , --fix-only]
        id: ruff-check
        name: 🐍 ruff · Check Python code
      - id: ruff-format
        name: 🐍 ruff · Format Python code
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.15
