from typing import overload

class Bond:
    @overload
    def __init__(
        self,
        settlementDays: int,
        calendar: Calendar,
        faceAmount: float,
        maturityDate: Date,
        issueDate: Date = ...,
        cashflows: list[CashFlow] = [],
    ) -> None: ...
    @overload
    def __init__(
        self,
        settlementDays: int,
        calendar: Calendar,
        issueDate: Date = ...,
        coupons: list[CashFlow] = [],
    ) -> None: ...
    def nextCouponRate(self, d: Date = ...) -> float: ...
    def previousCouponRate(self, d: Date = ...) -> float: ...
    def nextCashFlowDate(self, d: Date = ...) -> Date: ...
    def previousCashFlowDate(self, d: Date = ...) -> Date: ...
    def settlementDays(self) -> int: ...
    def settlementDate(self, d: Date = ...) -> Date: ...
    def isTradable(self, d: Date = ...) -> bool: ...
    def startDate(self) -> Date: ...
    def maturityDate(self) -> Date: ...
    def issueDate(self) -> Date: ...
    def cashflows(self) -> list[CashFlow]: ...
    def redemptions(self) -> list[CashFlow]: ...
    def redemption(self) -> CashFlow: ...
    def calendar(self) -> Calendar: ...
    def notionals(self) -> list[float]: ...
    def notional(self, d: Date = ...) -> float: ...
    @overload
    def cleanPrice(self) -> float: ...
    @overload
    def cleanPrice(
        self,
        yield_: float,
        dc: DayCounter,
        compounding: Compounding,
        frequency: Frequency,
        settlement: Date = ...,
    ) -> float: ...
    @overload
    def dirtyPrice(self) -> float: ...
    @overload
    def dirtyPrice(
        self,
        yield_: float,
        dc: DayCounter,
        compounding: Compounding,
        frequency: Frequency,
        settlement: Date = ...,
    ) -> float: ...
    @overload
    def yield_(
        self,
        dc: DayCounter,
        compounding: Compounding,
        freq: Frequency,
        accuracy: float = 1.0e-8,
        maxEvaluations: int = 100,
    ) -> float: ...
    @overload
    def yield_(
        self,
        price: BondPrice,
        dc: DayCounter,
        compounding: Compounding,
        freq: Frequency,
        settlement: Date = ...,
        accuracy: float = 1.0e-8,
        maxEvaluations: int = 100,
        guess: float = 0.05,
    ) -> float: ...
    def accruedAmount(self, settlement: Date = ...) -> float: ...
    @overload
    def settlementValue(self) -> float: ...
    @overload
    def settlementValue(self, cleanPrice: float) -> float: ...
