import typing
from typing import Any, Optional, overload
import collections.abc

class Weekday(int):
    Sunday: int = 1
    Monday: int = 2
    Tuesday: int = 3
    Wednesday: int = 4
    Thursday: int = 5
    Friday: int = 6
    Saturday: int = 7

class Month(int):
    January: int = 1
    February: int = 2
    March: int = 3
    April: int = 4
    May: int = 5
    June: int = 6
    July: int = 7
    August: int = 8
    September: int = 9
    October: int = 10
    November: int = 11
    December: int = 12

class TimeUnit(int):
    Days: int
    Weeks: int
    Months: int
    Years: int
    Hours: int
    Minutes: int
    Seconds: int
    Milliseconds: int
    Microseconds: int

class Frequency(int):
    NoFrequency: int = -1
    Once: int = 0
    Annual: int = 1
    Semiannual: int = 2
    EveryFourthMonth: int = 3
    Quarterly: int = 4
    Bimonthly: int = 6
    Monthly: int = 12
    EveryFourthWeek: int = 13
    Biweekly: int = 26
    Weekly: int = 52
    Daily: int = 365
    OtherFrequency: int = 999

class BusinessDayConvention(int):
    Following: int
    ModifiedFollowing: int
    Preceding: int
    ModifiedPreceding: int
    Unadjusted: int
    HalfMonthModifiedFollowing: int
    Nearest: int

class JointCalendarRule(int):
    JoinHolidays: int
    JoinBusinessDays: int

class Compounding(int):
    Simple: int
    Compounded: int
    Continuous: int
    SimpleThenCompounded: int
    CompoundedThenSimple: int

def daysBetween(arg0: Date, arg1: Date) -> float: ...
def nullInt() -> int: ...
def nullDouble() -> float: ...
def yearFractionToDate(dayCounter: DayCounter, referenceDate: Date, t: float) -> Date: ...
def inverse(m: Matrix) -> Matrix: ...
def transpose(m: Matrix) -> Matrix: ...
def outerProduct(v1: Array, v2: Array) -> Matrix: ...
def pseudoSqrt(m: Matrix, a: SalvagingAlgorithm.Type) -> Matrix: ...
@overload
def CholeskyDecomposition(m: Matrix) -> Matrix: ...
@overload
def CholeskyDecomposition(m: Matrix, flexible: bool) -> Matrix: ...
def CholeskySolveFor(L: Matrix, b: Array) -> Array: ...
@overload
def close(x: float, y: float) -> bool: ...
@overload
def close(x: float, y: float, n: int) -> bool: ...
@overload
def close_enough(x: float, y: float) -> bool: ...
@overload
def close_enough(x: float, y: float, n: int) -> bool: ...
class Period:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Frequency) -> None: ...
    @overload
    def __init__(self, n: int, units: TimeUnit) -> None: ...
    def length(self) -> int: ...
    def units(self) -> TimeUnit: ...
    def frequency(self) -> Frequency: ...
    def normalized(self) -> Period: ...

class Date:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, d: int, m: Month, y: int) -> None: ...
    @overload
    def __init__(self, serialNumber: int) -> None: ...
    def weekday(self) -> Weekday: ...
    def dayOfMonth(self) -> int: ...
    def dayOfYear(self) -> int: ...
    def month(self) -> Month: ...
    def year(self) -> int: ...
    def serialNumber(self) -> int: ...
    def isLeap(self, y: int) -> bool: ...
    def minDate(self) -> Date: ...
    def maxDate(self) -> Date: ...
    def todaysDate(self) -> Date: ...
    def startOfMonth(self, arg0: Date) -> Date: ...
    def endOfMonth(self, arg0: Date) -> Date: ...
    def isStartOfMonth(self, arg0: Date) -> bool: ...
    def isEndOfMonth(self, arg0: Date) -> bool: ...
    def nextWeekday(self, arg0: Date, arg1: Weekday) -> Date: ...
    def nthWeekday(self, n: int, arg1: Weekday, m: Month, y: int) -> Date: ...
    @overload
    def __add__(self, arg0: Period) -> Date: ...
    @overload
    def __add__(self, days: int) -> Date: ...
    @overload
    def __sub__(self, arg0: Period) -> Date: ...
    @overload
    def __sub__(self, days: int) -> Date: ...

class DateParser:
    def __init__(self) -> None: ...
    def parseFormatted(self, str: str, fmt: str) -> Date: ...
    def parseISO(self, str: str) -> Date: ...

class PeriodParser:
    def __init__(self) -> None: ...
    def parse(self, str: str) -> Period: ...

class IMM:
    class Month(int):
        F: int = 1
        G: int = 2
        H: int = 3
        J: int = 4
        K: int = 5
        M: int = 6
        N: int = 7
        Q: int = 8
        U: int = 9
        V: int = 10
        X: int = 11
        Z: int = 12
    
    def __init__(self) -> None: ...
    @overload
    def isIMMdate(self, d: Date) -> bool: ...
    @overload
    def isIMMdate(self, d: Date, mainCycle: bool) -> bool: ...
    @overload
    def isIMMcode(self, code: str) -> bool: ...
    @overload
    def isIMMcode(self, code: str, mainCycle: bool) -> bool: ...
    def code(self, immDate: Date) -> str: ...
    @overload
    def date(self, immCode: str) -> Date: ...
    @overload
    def date(self, immCode: str, referenceDate: Date) -> Date: ...
    @overload
    def nextDate(self) -> Date: ...
    @overload
    def nextDate(self, d: Date) -> Date: ...
    @overload
    def nextDate(self, d: Date, mainCycle: bool) -> Date: ...
    @overload
    def nextDate(self, immCode: str) -> Date: ...
    @overload
    def nextDate(self, immCode: str, mainCycle: bool) -> Date: ...
    @overload
    def nextDate(self, immCode: str, mainCycle: bool, referenceDate: Date) -> Date: ...
    @overload
    def nextCode(self) -> str: ...
    @overload
    def nextCode(self, d: Date) -> str: ...
    @overload
    def nextCode(self, d: Date, mainCycle: bool) -> str: ...
    @overload
    def nextCode(self, immCode: str) -> str: ...
    @overload
    def nextCode(self, immCode: str, mainCycle: bool) -> str: ...
    @overload
    def nextCode(self, immCode: str, mainCycle: bool, referenceDate: Date) -> str: ...

class ASX:
    class Month(int):
        F: int = 1
        G: int = 2
        H: int = 3
        J: int = 4
        K: int = 5
        M: int = 6
        N: int = 7
        Q: int = 8
        U: int = 9
        V: int = 10
        X: int = 11
        Z: int = 12
    
    def __init__(self) -> None: ...
    @overload
    def isASXdate(self, d: Date) -> bool: ...
    @overload
    def isASXdate(self, d: Date, mainCycle: bool) -> bool: ...
    @overload
    def isASXcode(self, code: str) -> bool: ...
    @overload
    def isASXcode(self, code: str, mainCycle: bool) -> bool: ...
    def code(self, asxDate: Date) -> str: ...
    @overload
    def date(self, asxCode: str) -> Date: ...
    @overload
    def date(self, asxCode: str, referenceDate: Date) -> Date: ...
    @overload
    def nextDate(self) -> Date: ...
    @overload
    def nextDate(self, asxCode: str) -> Date: ...
    @overload
    def nextDate(self, asxCode: str, mainCycle: bool) -> Date: ...
    @overload
    def nextDate(self, asxCode: str, mainCycle: bool, referenceDate: Date) -> Date: ...
    @overload
    def nextDate(self, d: Date) -> Date: ...
    @overload
    def nextDate(self, d: Date, mainCycle: bool) -> Date: ...
    @overload
    def nextCode(self) -> str: ...
    @overload
    def nextCode(self, asxCode: str) -> str: ...
    @overload
    def nextCode(self, asxCode: str, mainCycle: bool) -> str: ...
    @overload
    def nextCode(self, asxCode: str, mainCycle: bool, referenceDate: Date) -> str: ...
    @overload
    def nextCode(self, d: Date) -> str: ...
    @overload
    def nextCode(self, d: Date, mainCycle: bool) -> str: ...

class Calendar:
    def __init__(self) -> None: ...
    def isWeekend(self, w: Weekday) -> bool: ...
    def startOfMonth(self, arg0: Date) -> Date: ...
    def endOfMonth(self, arg0: Date) -> Date: ...
    def isBusinessDay(self, arg0: Date) -> bool: ...
    def isHoliday(self, arg0: Date) -> bool: ...
    def isEndOfMonth(self, arg0: Date) -> bool: ...
    def isStartOfMonth(self, arg0: Date) -> bool: ...
    def addHoliday(self, arg0: Date) -> None: ...
    def removeHoliday(self, arg0: Date) -> None: ...
    def resetAddedAndRemovedHolidays(self) -> None: ...
    @overload
    def adjust(self, d: Date) -> Date: ...
    @overload
    def adjust(self, d: Date, convention: BusinessDayConvention) -> Date: ...
    @overload
    def advance(self, d: Date, n: int, unit: TimeUnit) -> Date: ...
    @overload
    def advance(self, d: Date, n: int, unit: TimeUnit, convention: BusinessDayConvention) -> Date: ...
    @overload
    def advance(self, d: Date, n: int, unit: TimeUnit, convention: BusinessDayConvention, endOfMonth: bool) -> Date: ...
    @overload
    def advance(self, d: Date, period: Period) -> Date: ...
    @overload
    def advance(self, d: Date, period: Period, convention: BusinessDayConvention) -> Date: ...
    @overload
    def advance(self, d: Date, period: Period, convention: BusinessDayConvention, endOfMonth: bool) -> Date: ...
    @overload
    def businessDaysBetween(self, from_: Date, to: Date) -> int: ...
    @overload
    def businessDaysBetween(self, from_: Date, to: Date, includeFirst: bool) -> int: ...
    @overload
    def businessDaysBetween(self, from_: Date, to: Date, includeFirst: bool, includeLast: bool) -> int: ...
    @overload
    def holidayList(self, from_: Date, to: Date) -> typing.MutableSequence[Date]: ...
    @overload
    def holidayList(self, from_: Date, to: Date, includeWeekEnds: bool) -> typing.MutableSequence[Date]: ...
    def businessDayList(self, from_: Date, to: Date) -> typing.MutableSequence[Date]: ...
    def name(self) -> str: ...
    def empty(self) -> bool: ...

class Argentina(Calendar):
    class Market(int):
        Merval: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: Argentina.Market) -> None: ...

class Australia(Calendar):
    class Market(int):
        Settlement: int
        ASX: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, market: Australia.Market) -> None: ...

class Austria(Calendar):
    class Market(int):
        Settlement: int
        Exchange: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: Austria.Market) -> None: ...

class Botswana(Calendar):
    def __init__(self) -> None: ...

class Brazil(Calendar):
    class Market(int):
        Settlement: int
        Exchange: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: Brazil.Market) -> None: ...

class Canada(Calendar):
    class Market(int):
        Settlement: int
        TSX: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: Canada.Market) -> None: ...

class Chile(Calendar):
    class Market(int):
        SSE: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: Chile.Market) -> None: ...

class China(Calendar):
    class Market(int):
        SSE: int
        IB: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: China.Market) -> None: ...

class CzechRepublic(Calendar):
    class Market(int):
        PSE: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: CzechRepublic.Market) -> None: ...

class Denmark(Calendar):
    def __init__(self) -> None: ...

class Finland(Calendar):
    def __init__(self) -> None: ...

class France(Calendar):
    class Market(int):
        Settlement: int
        Exchange: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: France.Market) -> None: ...

class Germany(Calendar):
    class Market(int):
        Settlement: int
        FrankfurtStockExchange: int
        Xetra: int
        Eurex: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: Germany.Market) -> None: ...

class HongKong(Calendar):
    class Market(int):
        HKEx: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: HongKong.Market) -> None: ...

class Hungary(Calendar):
    def __init__(self) -> None: ...

class Iceland(Calendar):
    class Market(int):
        ICEX: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: Iceland.Market) -> None: ...

class India(Calendar):
    class Market(int):
        NSE: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: India.Market) -> None: ...

class Indonesia(Calendar):
    class Market(int):
        BEJ: int
        JSX: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: Indonesia.Market) -> None: ...

class Israel(Calendar):
    class Market(int):
        Settlement: int
        TASE: int
        SHIR: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: Israel.Market) -> None: ...

class Italy(Calendar):
    class Market(int):
        Settlement: int
        Exchange: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: Italy.Market) -> None: ...

class Japan(Calendar):
    def __init__(self) -> None: ...

class Mexico(Calendar):
    class Market(int):
        BMV: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: Mexico.Market) -> None: ...

class NewZealand(Calendar):
    class Market(int):
        Wellington: int
        Auckland: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: NewZealand.Market) -> None: ...

class Norway(Calendar):
    def __init__(self) -> None: ...

class Poland(Calendar):
    class Market(int):
        Settlement: int
        WSE: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: Poland.Market) -> None: ...

class Romania(Calendar):
    class Market(int):
        Public: int
        BVB: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: Romania.Market) -> None: ...

class Russia(Calendar):
    class Market(int):
        Settlement: int
        MOEX: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: Russia.Market) -> None: ...

class SaudiArabia(Calendar):
    class Market(int):
        Tadawul: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: SaudiArabia.Market) -> None: ...

class Singapore(Calendar):
    class Market(int):
        SGX: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: Singapore.Market) -> None: ...

class Slovakia(Calendar):
    class Market(int):
        BSSE: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: Slovakia.Market) -> None: ...

class SouthAfrica(Calendar):
    def __init__(self) -> None: ...

class SouthKorea(Calendar):
    class Market(int):
        Settlement: int
        KRX: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: SouthKorea.Market) -> None: ...

class Sweden(Calendar):
    def __init__(self) -> None: ...

class Switzerland(Calendar):
    def __init__(self) -> None: ...

class Taiwan(Calendar):
    class Market(int):
        TSEC: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: Taiwan.Market) -> None: ...

class TARGET(Calendar):
    def __init__(self) -> None: ...

class Thailand(Calendar):
    def __init__(self) -> None: ...

class Turkey(Calendar):
    def __init__(self) -> None: ...

class Ukraine(Calendar):
    class Market(int):
        USE: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: Ukraine.Market) -> None: ...

class UnitedKingdom(Calendar):
    class Market(int):
        Settlement: int
        Exchange: int
        Metals: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m: UnitedKingdom.Market) -> None: ...

class UnitedStates(Calendar):
    class Market(int):
        Settlement: int
        NYSE: int
        GovernmentBond: int
        NERC: int
        LiborImpact: int
        FederalReserve: int
        SOFR: int
    
    def __init__(self, m: UnitedStates.Market) -> None: ...

class NullCalendar(Calendar):
    def __init__(self) -> None: ...

class WeekendsOnly(Calendar):
    def __init__(self) -> None: ...

class JointCalendar(Calendar):
    @overload
    def __init__(self, arg0: Calendar, arg1: Calendar) -> None: ...
    @overload
    def __init__(self, arg0: Calendar, arg1: Calendar, arg2: Calendar) -> None: ...
    @overload
    def __init__(self, arg0: Calendar, arg1: Calendar, arg2: Calendar, arg3: Calendar) -> None: ...
    @overload
    def __init__(self, arg0: Calendar, arg1: Calendar, arg2: Calendar, arg3: Calendar, rule: JointCalendarRule) -> None: ...
    @overload
    def __init__(self, arg0: Calendar, arg1: Calendar, arg2: Calendar, rule: JointCalendarRule) -> None: ...
    @overload
    def __init__(self, arg0: Calendar, arg1: Calendar, rule: JointCalendarRule) -> None: ...
    @overload
    def __init__(self, arg0: typing.MutableSequence[Calendar]) -> None: ...
    @overload
    def __init__(self, arg0: typing.MutableSequence[Calendar], arg1: JointCalendarRule) -> None: ...

class BespokeCalendar(Calendar):
    def __init__(self, name: str) -> None: ...
    def addWeekend(self, arg0: Weekday) -> None: ...

class DayCounter:
    def __init__(self) -> None: ...
    def dayCount(self, d1: Date, d2: Date) -> int: ...
    @overload
    def yearFraction(self, d1: Date, d2: Date) -> float: ...
    @overload
    def yearFraction(self, d1: Date, d2: Date, startRef: Date) -> float: ...
    @overload
    def yearFraction(self, d1: Date, d2: Date, startRef: Date, endRef: Date) -> float: ...
    def name(self) -> str: ...
    def empty(self) -> bool: ...

class Actual360(DayCounter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, includeLastDay: bool) -> None: ...

class Actual366(DayCounter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, includeLastDay: bool) -> None: ...

class Actual36525(DayCounter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, includeLastDay: bool) -> None: ...

class Actual364(DayCounter):
    def __init__(self) -> None: ...

class Actual365Fixed(DayCounter):
    class Convention(int):
        Standard: int
        Canadian: int
        NoLeap: int
    
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, c: Actual365Fixed.Convention) -> None: ...

class Thirty360(DayCounter):
    class Convention(int):
        USA: int
        BondBasis: int
        European: int
        EurobondBasis: int
        Italian: int
        German: int
        ISMA: int
        ISDA: int
        NASD: int
    
    @overload
    def __init__(self, c: Thirty360.Convention) -> None: ...
    @overload
    def __init__(self, c: Thirty360.Convention, terminationDate: Date) -> None: ...

class Thirty365(DayCounter):
    def __init__(self) -> None: ...

class ActualActual(DayCounter):
    class Convention(int):
        ISMA: int
        Bond: int
        ISDA: int
        Historical: int
        Actual365: int
        AFB: int
        Euro: int
    
    @overload
    def __init__(self, c: ActualActual.Convention) -> None: ...
    @overload
    def __init__(self, c: ActualActual.Convention, schedule: Schedule) -> None: ...

class OneDayCounter(DayCounter):
    def __init__(self) -> None: ...

class SimpleDayCounter(DayCounter):
    def __init__(self) -> None: ...

class Business252(DayCounter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, c: Calendar) -> None: ...

class Observable:
    def __init__(self) -> None: ...

class Array:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Array) -> None: ...
    @overload
    def __init__(self, n: int) -> None: ...
    @overload
    def __init__(self, n: int, fill: float) -> None: ...
    def size(self) -> int: ...

class Matrix:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Matrix) -> None: ...
    @overload
    def __init__(self, rows: int, columns: int) -> None: ...
    @overload
    def __init__(self, rows: int, columns: int, fill: float) -> None: ...
    def rows(self) -> int: ...
    def columns(self) -> int: ...

class SalvagingAlgorithm:
    class Type(int):
        None: int
        Spectral: int
        Hypersphere: int
        LowerDiagonal: int
        Higham: int
        Principal: int
    
    def __init__(self) -> None: ...

class SVD:
    def __init__(self, arg0: Matrix) -> None: ...
    def U(self) -> Matrix: ...
    def V(self) -> Matrix: ...
    def S(self) -> Matrix: ...
    def singularValues(self) -> Array: ...

class SymmetricSchurDecomposition:
    def __init__(self, s: Matrix) -> None: ...
    def eigenvalues(self) -> Array: ...
    def eigenvectors(self) -> Matrix: ...

class DefaultBoundaryCondition:
    class Side(int):
        None: int
        Upper: int
        Lower: int
    
    def __init__(self) -> None: ...

class NeumannBC(DefaultBoundaryCondition):
    def __init__(self, value: float, side: DefaultBoundaryCondition.Side) -> None: ...

class DirichletBC(DefaultBoundaryCondition):
    def __init__(self, value: float, side: DefaultBoundaryCondition.Side) -> None: ...

class TridiagonalOperator:
    def __init__(self, low: Array, mid: Array, high: Array) -> None: ...
    def solveFor(self, rhs: Array) -> Array: ...
    def applyTo(self, v: Array) -> Array: ...
    def size(self) -> int: ...
    def setFirstRow(self, arg0: float, arg1: float) -> None: ...
    def setMidRow(self, arg0: int, arg1: float, arg2: float, arg3: float) -> None: ...
    def setMidRows(self, arg0: float, arg1: float, arg2: float) -> None: ...
    def setLastRow(self, arg0: float, arg1: float) -> None: ...
    def identity(self, size: int) -> TridiagonalOperator: ...

class DPlus(TridiagonalOperator):
    def __init__(self, gridPoints: int, h: float) -> None: ...

class DMinus(TridiagonalOperator):
    def __init__(self, gridPoints: int, h: float) -> None: ...

class DZero(TridiagonalOperator):
    def __init__(self, gridPoints: int, h: float) -> None: ...

class DPlusDMinus(TridiagonalOperator):
    def __init__(self, gridPoints: int, h: float) -> None: ...

class SegmentIntegral:
    def __init__(self, intervals: int) -> None: ...
    def numberOfEvaluations(self) -> int: ...

class SimpsonIntegral:
    def __init__(self, accuracy: float, maxIterations: int) -> None: ...
    def numberOfEvaluations(self) -> int: ...

class GaussKronrodAdaptive:
    @overload
    def __init__(self, tolerance: float) -> None: ...
    @overload
    def __init__(self, tolerance: float, maxFunctionEvaluations: int) -> None: ...
    def numberOfEvaluations(self) -> int: ...

class GaussKronrodNonAdaptive:
    def __init__(self, absoluteAccuracy: float, maxEvaluations: int, relativeAccuracy: float) -> None: ...
    def numberOfEvaluations(self) -> int: ...

class GaussLobattoIntegral:
    @overload
    def __init__(self, maxIterations: int, absAccuracy: float) -> None: ...
    @overload
    def __init__(self, maxIterations: int, absAccuracy: float, relAccuracy: float) -> None: ...
    @overload
    def __init__(self, maxIterations: int, absAccuracy: float, relAccuracy: float, useConvergenceEstimate: bool) -> None: ...
    def numberOfEvaluations(self) -> int: ...

class GaussianQuadrature:
    def __init__(self) -> None: ...
    def order(self) -> int: ...

class GaussLaguerreIntegration(GaussianQuadrature):
    @overload
    def __init__(self, n: int) -> None: ...
    @overload
    def __init__(self, n: int, s: float) -> None: ...

class GaussHermiteIntegration(GaussianQuadrature):
    @overload
    def __init__(self, n: int) -> None: ...
    @overload
    def __init__(self, n: int, mu: float) -> None: ...

class GaussJacobiIntegration(GaussianQuadrature):
    def __init__(self, n: int, alpha: float, beta: float) -> None: ...

class GaussHyperbolicIntegration(GaussianQuadrature):
    def __init__(self, n: int) -> None: ...

class GaussLegendreIntegration(GaussianQuadrature):
    def __init__(self, n: int) -> None: ...

class GaussChebyshevIntegration(GaussianQuadrature):
    def __init__(self, n: int) -> None: ...

class GaussChebyshev2ndIntegration(GaussianQuadrature):
    def __init__(self, n: int) -> None: ...

class GaussGegenbauerIntegration(GaussianQuadrature):
    def __init__(self, n: int, lambda_: float) -> None: ...

class TanhSinhIntegral:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, relTolerance: float) -> None: ...
    @overload
    def __init__(self, relTolerance: float, maxRefinements: int) -> None: ...
    @overload
    def __init__(self, relTolerance: float, maxRefinements: int, minComplement: float) -> None: ...
    def numberOfEvaluations(self) -> int: ...

class ExpSinhIntegral:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, relTolerance: float) -> None: ...
    @overload
    def __init__(self, relTolerance: float, maxRefinements: int) -> None: ...
    def numberOfEvaluations(self) -> int: ...

class InterestRate:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, r: float, dc: DayCounter, comp: Compounding, freq: Frequency) -> None: ...
    def rate(self) -> float: ...
    def dayCounter(self) -> DayCounter: ...
    def compounding(self) -> Compounding: ...
    def frequency(self) -> Frequency: ...
    @overload
    def discountFactor(self, d1: Date, d2: Date) -> DiscountFactor: ...
    @overload
    def discountFactor(self, d1: Date, d2: Date, refStart: Date) -> DiscountFactor: ...
    @overload
    def discountFactor(self, d1: Date, d2: Date, refStart: Date, refEnd: Date) -> DiscountFactor: ...
    @overload
    def discountFactor(self, t: float) -> DiscountFactor: ...
    @overload
    def compoundFactor(self, d1: Date, d2: Date) -> float: ...
    @overload
    def compoundFactor(self, d1: Date, d2: Date, refStart: Date) -> float: ...
    @overload
    def compoundFactor(self, d1: Date, d2: Date, refStart: Date, refEnd: Date) -> float: ...
    @overload
    def compoundFactor(self, t: float) -> float: ...
    @overload
    def impliedRate(self, compound: float, resultDC: DayCounter, comp: Compounding, freq: Frequency, d1: Date, d2: Date) -> InterestRate: ...
    @overload
    def impliedRate(self, compound: float, resultDC: DayCounter, comp: Compounding, freq: Frequency, d1: Date, d2: Date, refStart: Date) -> InterestRate: ...
    @overload
    def impliedRate(self, compound: float, resultDC: DayCounter, comp: Compounding, freq: Frequency, d1: Date, d2: Date, refStart: Date, refEnd: Date) -> InterestRate: ...
    @overload
    def impliedRate(self, compound: float, resultDC: DayCounter, comp: Compounding, freq: Frequency, t: float) -> InterestRate: ...
    @overload
    def equivalentRate(self, comp: Compounding, freq: Frequency, t: float) -> InterestRate: ...
    @overload
    def equivalentRate(self, resultDayCounter: DayCounter, comp: Compounding, freq: Frequency, d1: Date, d2: Date) -> InterestRate: ...
    @overload
    def equivalentRate(self, resultDayCounter: DayCounter, comp: Compounding, freq: Frequency, d1: Date, d2: Date, refStart: Date) -> InterestRate: ...
    @overload
    def equivalentRate(self, resultDayCounter: DayCounter, comp: Compounding, freq: Frequency, d1: Date, d2: Date, refStart: Date, refEnd: Date) -> InterestRate: ...

class Brent:
    def __init__(self) -> None: ...
    def setMaxEvaluations(self, evaluations: int) -> None: ...
    def setLowerBound(self, lowerBound: float) -> None: ...
    def setUpperBound(self, upperBound: float) -> None: ...

class Bisection:
    def __init__(self) -> None: ...
    def setMaxEvaluations(self, evaluations: int) -> None: ...
    def setLowerBound(self, lowerBound: float) -> None: ...
    def setUpperBound(self, upperBound: float) -> None: ...

class FalsePosition:
    def __init__(self) -> None: ...
    def setMaxEvaluations(self, evaluations: int) -> None: ...
    def setLowerBound(self, lowerBound: float) -> None: ...
    def setUpperBound(self, upperBound: float) -> None: ...

class Ridder:
    def __init__(self) -> None: ...
    def setMaxEvaluations(self, evaluations: int) -> None: ...
    def setLowerBound(self, lowerBound: float) -> None: ...
    def setUpperBound(self, upperBound: float) -> None: ...

class Secant:
    def __init__(self) -> None: ...
    def setMaxEvaluations(self, evaluations: int) -> None: ...
    def setLowerBound(self, lowerBound: float) -> None: ...
    def setUpperBound(self, upperBound: float) -> None: ...

class Constraint:
    def __init__(self) -> None: ...

class BoundaryConstraint(Constraint):
    def __init__(self, lower: float, upper: float) -> None: ...

class NoConstraint(Constraint):
    def __init__(self) -> None: ...

class PositiveConstraint(Constraint):
    def __init__(self) -> None: ...

class CompositeConstraint(Constraint):
    def __init__(self, c1: Constraint, c2: Constraint) -> None: ...

class NonhomogeneousBoundaryConstraint(Constraint):
    def __init__(self, l: Array, u: Array) -> None: ...

class EndCriteria:
    class Type(int):
        None: int
        MaxIterations: int
        StationaryPoint: int
        StationaryFunctionValue: int
        StationaryFunctionAccuracy: int
        ZeroGradientNorm: int
        FunctionEpsilonTooSmall: int
        Unknown: int
    
    def __init__(self, maxIteration: int, maxStationaryStateIterations: int, rootEpsilon: float, functionEpsilon: float, gradientNormEpsilon: float) -> None: ...
    def succeeded(self, ecType: EndCriteria.Type) -> bool: ...

class OptimizationMethod:
    def __init__(self) -> None: ...

class ConjugateGradient(OptimizationMethod):
    def __init__(self) -> None: ...

class Simplex(OptimizationMethod):
    def __init__(self, lambda_: float) -> None: ...
    def lambda(self) -> float: ...

class SteepestDescent(OptimizationMethod):
    def __init__(self) -> None: ...

class BFGS(OptimizationMethod):
    def __init__(self) -> None: ...

class LevenbergMarquardt(OptimizationMethod):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, epsfcn: float) -> None: ...
    @overload
    def __init__(self, epsfcn: float, xtol: float) -> None: ...
    @overload
    def __init__(self, epsfcn: float, xtol: float, gtol: float) -> None: ...
    @overload
    def __init__(self, epsfcn: float, xtol: float, gtol: float, useCostFunctionsJacobian: bool) -> None: ...

class DifferentialEvolution(OptimizationMethod):
    def __init__(self) -> None: ...

class SamplerGaussian:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, seed: int) -> None: ...

class SamplerLogNormal:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, seed: int) -> None: ...

class SamplerMirrorGaussian:
    @overload
    def __init__(self, lower: Array, upper: Array) -> None: ...
    @overload
    def __init__(self, lower: Array, upper: Array, seed: int) -> None: ...

class ProbabilityBoltzmannDownhill:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, seed: int) -> None: ...

class TemperatureExponential:
    @overload
    def __init__(self, initialTemp: float, dimension: int) -> None: ...
    @overload
    def __init__(self, initialTemp: float, dimension: int, power: float) -> None: ...

class ReannealingTrivial:
    def __init__(self) -> None: ...

class GaussianSimulatedAnnealing(OptimizationMethod):
    class ResetScheme(int):
        NoResetScheme: int
        ResetToBestPoint: int
        ResetToOrigin: int
    
    @overload
    def __init__(self, sampler: SamplerGaussian, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential) -> None: ...
    @overload
    def __init__(self, sampler: SamplerGaussian, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential, reannealing: ReannealingTrivial) -> None: ...
    @overload
    def __init__(self, sampler: SamplerGaussian, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential, reannealing: ReannealingTrivial, startTemperature: float) -> None: ...
    @overload
    def __init__(self, sampler: SamplerGaussian, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential, reannealing: ReannealingTrivial, startTemperature: float, endTemperature: float) -> None: ...
    @overload
    def __init__(self, sampler: SamplerGaussian, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential, reannealing: ReannealingTrivial, startTemperature: float, endTemperature: float, reAnnealSteps: int) -> None: ...
    @overload
    def __init__(self, sampler: SamplerGaussian, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential, reannealing: ReannealingTrivial, startTemperature: float, endTemperature: float, reAnnealSteps: int, resetScheme: GaussianSimulatedAnnealing.ResetScheme) -> None: ...
    @overload
    def __init__(self, sampler: SamplerGaussian, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential, reannealing: ReannealingTrivial, startTemperature: float, endTemperature: float, reAnnealSteps: int, resetScheme: GaussianSimulatedAnnealing.ResetScheme, resetSteps: int) -> None: ...

class MirrorGaussianSimulatedAnnealing(OptimizationMethod):
    class ResetScheme(int):
        NoResetScheme: int
        ResetToBestPoint: int
        ResetToOrigin: int
    
    @overload
    def __init__(self, sampler: SamplerMirrorGaussian, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential) -> None: ...
    @overload
    def __init__(self, sampler: SamplerMirrorGaussian, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential, reannealing: ReannealingTrivial) -> None: ...
    @overload
    def __init__(self, sampler: SamplerMirrorGaussian, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential, reannealing: ReannealingTrivial, startTemperature: float) -> None: ...
    @overload
    def __init__(self, sampler: SamplerMirrorGaussian, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential, reannealing: ReannealingTrivial, startTemperature: float, endTemperature: float) -> None: ...
    @overload
    def __init__(self, sampler: SamplerMirrorGaussian, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential, reannealing: ReannealingTrivial, startTemperature: float, endTemperature: float, reAnnealSteps: int) -> None: ...
    @overload
    def __init__(self, sampler: SamplerMirrorGaussian, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential, reannealing: ReannealingTrivial, startTemperature: float, endTemperature: float, reAnnealSteps: int, resetScheme: MirrorGaussianSimulatedAnnealing.ResetScheme) -> None: ...
    @overload
    def __init__(self, sampler: SamplerMirrorGaussian, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential, reannealing: ReannealingTrivial, startTemperature: float, endTemperature: float, reAnnealSteps: int, resetScheme: MirrorGaussianSimulatedAnnealing.ResetScheme, resetSteps: int) -> None: ...

class LogNormalSimulatedAnnealing(OptimizationMethod):
    class ResetScheme(int):
        NoResetScheme: int
        ResetToBestPoint: int
        ResetToOrigin: int
    
    @overload
    def __init__(self, sampler: SamplerLogNormal, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential) -> None: ...
    @overload
    def __init__(self, sampler: SamplerLogNormal, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential, reannealing: ReannealingTrivial) -> None: ...
    @overload
    def __init__(self, sampler: SamplerLogNormal, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential, reannealing: ReannealingTrivial, startTemperature: float) -> None: ...
    @overload
    def __init__(self, sampler: SamplerLogNormal, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential, reannealing: ReannealingTrivial, startTemperature: float, endTemperature: float) -> None: ...
    @overload
    def __init__(self, sampler: SamplerLogNormal, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential, reannealing: ReannealingTrivial, startTemperature: float, endTemperature: float, reAnnealSteps: int) -> None: ...
    @overload
    def __init__(self, sampler: SamplerLogNormal, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential, reannealing: ReannealingTrivial, startTemperature: float, endTemperature: float, reAnnealSteps: int, resetScheme: LogNormalSimulatedAnnealing.ResetScheme) -> None: ...
    @overload
    def __init__(self, sampler: SamplerLogNormal, probability: ProbabilityBoltzmannDownhill, temperature: TemperatureExponential, reannealing: ReannealingTrivial, startTemperature: float, endTemperature: float, reAnnealSteps: int, resetScheme: LogNormalSimulatedAnnealing.ResetScheme, resetSteps: int) -> None: ...

class Optimizer:
    def __init__(self) -> None: ...

class SafeLinearInterpolation:
    def __init__(self, x: Array, y: Array) -> None: ...
    @overload
    def __call__(self, x: float) -> float: ...
    @overload
    def __call__(self, x: float, allowExtrapolation: bool) -> float: ...

class SafeLogLinearInterpolation:
    def __init__(self, x: Array, y: Array) -> None: ...
    @overload
    def __call__(self, x: float) -> float: ...
    @overload
    def __call__(self, x: float, allowExtrapolation: bool) -> float: ...

class SafeBackwardFlatInterpolation:
    def __init__(self, x: Array, y: Array) -> None: ...
    @overload
    def __call__(self, x: float) -> float: ...
    @overload
    def __call__(self, x: float, allowExtrapolation: bool) -> float: ...

class SafeForwardFlatInterpolation:
    def __init__(self, x: Array, y: Array) -> None: ...
    @overload
    def __call__(self, x: float) -> float: ...
    @overload
    def __call__(self, x: float, allowExtrapolation: bool) -> float: ...

class SafeCubicNaturalSpline:
    def __init__(self, x: Array, y: Array) -> None: ...
    @overload
    def __call__(self, x: float) -> float: ...
    @overload
    def __call__(self, x: float, allowExtrapolation: bool) -> float: ...

class SafeLogCubicNaturalSpline:
    def __init__(self, x: Array, y: Array) -> None: ...
    @overload
    def __call__(self, x: float) -> float: ...
    @overload
    def __call__(self, x: float, allowExtrapolation: bool) -> float: ...

class SafeMonotonicCubicNaturalSpline:
    def __init__(self, x: Array, y: Array) -> None: ...
    @overload
    def __call__(self, x: float) -> float: ...
    @overload
    def __call__(self, x: float, allowExtrapolation: bool) -> float: ...

class SafeMonotonicLogCubicNaturalSpline:
    def __init__(self, x: Array, y: Array) -> None: ...
    @overload
    def __call__(self, x: float) -> float: ...
    @overload
    def __call__(self, x: float, allowExtrapolation: bool) -> float: ...

class SafeKrugerCubic:
    def __init__(self, x: Array, y: Array) -> None: ...
    @overload
    def __call__(self, x: float) -> float: ...
    @overload
    def __call__(self, x: float, allowExtrapolation: bool) -> float: ...

class SafeKrugerLogCubic:
    def __init__(self, x: Array, y: Array) -> None: ...
    @overload
    def __call__(self, x: float) -> float: ...
    @overload
    def __call__(self, x: float, allowExtrapolation: bool) -> float: ...

class SafeFritschButlandCubic:
    def __init__(self, x: Array, y: Array) -> None: ...
    @overload
    def __call__(self, x: float) -> float: ...
    @overload
    def __call__(self, x: float, allowExtrapolation: bool) -> float: ...

class SafeFritschButlandLogCubic:
    def __init__(self, x: Array, y: Array) -> None: ...
    @overload
    def __call__(self, x: float) -> float: ...
    @overload
    def __call__(self, x: float, allowExtrapolation: bool) -> float: ...

class SafeParabolic:
    def __init__(self, x: Array, y: Array) -> None: ...
    @overload
    def __call__(self, x: float) -> float: ...
    @overload
    def __call__(self, x: float, allowExtrapolation: bool) -> float: ...

class SafeLogParabolic:
    def __init__(self, x: Array, y: Array) -> None: ...
    @overload
    def __call__(self, x: float) -> float: ...
    @overload
    def __call__(self, x: float, allowExtrapolation: bool) -> float: ...

class SafeMonotonicParabolic:
    def __init__(self, x: Array, y: Array) -> None: ...
    @overload
    def __call__(self, x: float) -> float: ...
    @overload
    def __call__(self, x: float, allowExtrapolation: bool) -> float: ...

class SafeMonotonicLogParabolic:
    def __init__(self, x: Array, y: Array) -> None: ...
    @overload
    def __call__(self, x: float) -> float: ...
    @overload
    def __call__(self, x: float, allowExtrapolation: bool) -> float: ...

class SafeLagrangeInterpolation:
    def __init__(self, x: Array, y: Array) -> None: ...
    @overload
    def __call__(self, x: float) -> float: ...
    @overload
    def __call__(self, x: float, allowExtrapolation: bool) -> float: ...

class SafeBilinearInterpolation:
    def __init__(self, x: Array, y: Array, m: Matrix) -> None: ...
    @overload
    def __call__(self, x: float, y: float) -> float: ...
    @overload
    def __call__(self, x: float, y: float, allowExtrapolation: bool) -> float: ...

class SafeBicubicSpline:
    def __init__(self, x: Array, y: Array, m: Matrix) -> None: ...
    @overload
    def __call__(self, x: float, y: float) -> float: ...
    @overload
    def __call__(self, x: float, y: float, allowExtrapolation: bool) -> float: ...

class CubicInterpolation:
    class DerivativeApprox(int):
        Spline: int
        SplineOM1: int
        SplineOM2: int
        FourthOrder: int
        Parabolic: int
        FritschButland: int
        Akima: int
        Kruger: int
        Harmonic: int
    

class MixedInterpolation:
    class Behavior(int):
        ShareRanges: int
        SplitRanges: int
    

class BackwardFlat:
    def __init__(self) -> None: ...

class ForwardFlat:
    def __init__(self) -> None: ...

class Linear:
    def __init__(self) -> None: ...

class LogLinear:
    def __init__(self) -> None: ...

class Cubic:
    def __init__(self) -> None: ...

class Bicubic:
    def __init__(self) -> None: ...

class MonotonicCubic:
    def __init__(self) -> None: ...

class DefaultLogCubic:
    def __init__(self) -> None: ...

class MonotonicLogCubic:
    def __init__(self) -> None: ...

class SplineCubic:
    def __init__(self) -> None: ...

class SplineLogCubic:
    def __init__(self) -> None: ...

class Kruger:
    def __init__(self) -> None: ...

class KrugerLog:
    def __init__(self) -> None: ...

class ConvexMonotone:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, quadraticity: float) -> None: ...
    @overload
    def __init__(self, quadraticity: float, monotonicity: float) -> None: ...
    @overload
    def __init__(self, quadraticity: float, monotonicity: float, forcePositive: bool) -> None: ...

class ParabolicCubic:
    def __init__(self) -> None: ...

class MonotonicParabolicCubic:
    def __init__(self) -> None: ...

class LogParabolicCubic:
    def __init__(self) -> None: ...

class MonotonicLogParabolicCubic:
    def __init__(self) -> None: ...

class LogMixedLinearCubic:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, n: int) -> None: ...
    @overload
    def __init__(self, n: int, behavior: MixedInterpolation.Behavior) -> None: ...
    @overload
    def __init__(self, n: int, behavior: MixedInterpolation.Behavior, da: CubicInterpolation.DerivativeApprox) -> None: ...
    @overload
    def __init__(self, n: int, behavior: MixedInterpolation.Behavior, da: CubicInterpolation.DerivativeApprox, monotonic: bool) -> None: ...

class RichardsonExtrapolation:
    def __init__(self) -> None: ...
    @overload
    def __call__(self) -> float: ...
    @overload
    def __call__(self, t: float) -> float: ...
    @overload
    def __call__(self, t: float, s: float) -> float: ...

class ChebyshevInterpolation:
    class PointsType(int):
        FirstKind: int
        SecondKind: int
    
    @overload
    def __init__(self, f: Array) -> None: ...
    @overload
    def __init__(self, f: Array, pointsType: ChebyshevInterpolation.PointsType) -> None: ...
    @overload
    def __call__(self, z: float) -> float: ...
    @overload
    def __call__(self, z: float, allowExtrapolation: bool) -> float: ...
    def nodes(self, n: int, pointsType: ChebyshevInterpolation.PointsType) -> Array: ...

class SafeConvexMonotoneInterpolation:
    @overload
    def __init__(self, x: Array, y: Array) -> None: ...
    @overload
    def __init__(self, x: Array, y: Array, quadraticity: float) -> None: ...
    @overload
    def __init__(self, x: Array, y: Array, quadraticity: float, monotonicity: float) -> None: ...
    @overload
    def __init__(self, x: Array, y: Array, quadraticity: float, monotonicity: float, forcePositive: bool) -> None: ...
    @overload
    def __call__(self, x: float) -> float: ...
    @overload
    def __call__(self, x: float, allowExtrapolation: bool) -> float: ...

class LazyObject(Observable):
    def __init__(self) -> None: ...
    def recalculate(self) -> None: ...
    def freeze(self) -> None: ...
    def unfreeze(self) -> None: ...
