import typing
from typing import Any, Optional, overload, Generic, TypeVar
from enum import IntEnum
import collections.abc

_T = TypeVar('_T')

class Handle(Generic[_T]):
    def __init__(self, p: Optional[_T] = ...) -> None: ...
    def currentLink(self) -> _T: ...
    def empty(self) -> bool: ...
    def __deref__(self) -> _T: ...
class RelinkableHandle(Handle[_T]):
    def linkTo(self, h: _T, registerAsObserver: bool = True) -> None: ...
class TimeSeries(Generic[_T]):
    def __init__(self) -> None: ...
